# Preprocessing Pipeline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/TIH_IIT_Intern_Work/Dataset.csv")

df.head()

   S No  binary bit R  Binary bit S  Analog value  Analog Voltage     NTU
0     1             1             1           125        0.610352  1-2NTU
1     2             0             0           101        0.493164  1-2NTU
2     3             1             1           123        0.600586  1-2NTU
3     4             0             0           101        0.493164  1-2NTU
4     5             0             0            95        0.463867  1-2NTU

## 1. Drop Unnecessary Column

In [ ]:
df = df.drop(
    columns=["S No"]
)

## 2. Encode NTU

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["NTU"] = encoder.fit_transform(
    df["NTU"]
)

df.head()

   binary bit R  Binary bit S  Analog value  Analog Voltage  NTU
0             1             1           125        0.610352    0
1             0             0           101        0.493164    0
2             1             1           123        0.600586    0
3             0             0           101        0.493164    0
4             0             0            95        0.463867    0

## 3. Define Features & Target

In [ ]:
X = df[
    [
        "Analog value",
        "Analog Voltage",
        "NTU"
    ]
]

y = df["Binary bit S"]

## 4. Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(279, 3)
(120, 3)

## 5. Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(
    X_train
)

X_test = scaler.transform(
    X_test
)

## 6. Preprocessed Data

In [ ]:
x_train = pd.DataFrame(X_train, columns=["Analog value", "Analog Voltage", "NTU"])
x_test = pd.DataFrame(X_test, columns=["Analog value", "Analog Voltage", "NTU"])

x_train.head()

   Analog value  Analog Voltage       NTU
0     -0.895865       -0.895865  1.509531
1      0.996565        0.996565 -1.360378
2     -0.750293       -0.750293  1.509531
3     -0.556198       -0.556198  1.509531
4      1.142136        1.142136 -1.360378

In [ ]:
x_train.to_csv('x_train_preprocessed.csv', index=False)
print('x_train_preprocessed.csv has been saved. You can download it from the file explorer on the left.')

x_train_preprocessed.csv has been saved. You can download it from the file explorer on the left.

In [ ]:
x_test.to_csv('x_test_preprocessed.csv', index=False)
print('x_test_preprocessed.csv has been saved. You can download it from the file explorer on the left.')

x_test_preprocessed.csv has been saved. You can download it from the file explorer on the left.

In [ ]:
y_test.to_csv('y_test_preprocessed.csv', index=False)
print('y_test_preprocessed.csv has been saved. You can download it from the file explorer on the left.')

y_test_preprocessed.csv has been saved. You can download it from the file explorer on the left.

In [ ]:
y_train.to_csv('y_train_preprocessed.csv', index=False)
print('y_train_preprocessed.csv has been saved. You can download it from the file explorer on the left.')

y_train_preprocessed.csv has been saved. You can download it from the file explorer on the left.